import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { FloatingNavDemo } from "./floating-nav";
import Footer from "@/components/footer";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
      <FloatingNavDemo/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
